---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/shashankkoppar/concourse-tutorial.git
      branch: test-concourse
jobs:
  - name: job-hello-world
    public: true
    plan:
    - get: resource-tutorial
    - task: get-files
      config:
        platform: linux
        inputs:
        - name: resource-tutorial
        outputs:
        - name: some-files
        image_resource:
          type: docker-image
          source:
            repository: eu.gcr.io/xite-cms/kopparr
            username: _json_key
            password: ((gcloud-service-account-key-file))
        run:
          path: /bin/bash
          args:
          - -exc
          - |
            ./resource-tutorial/tutorials/basic/basic-pipeline/gcloudbuild.sh
        params:
          GCLOUD_SERVICE_ACCOUNT_KEY_FILE: ((gcloud-service-account-key-file))
params:
  GCLOUD_SERVICE_ACCOUNT_KEY_FILE: ((gcloud-service-account-key-file))
