---
resources:
  - name: tutorial
    type: git
    source:
      uri: https://github.com/drnic/concourse-tutorial.git
      branch: develop
jobs:
  - name: publish
    public: true
    plan:
      - get: tutorial
      - task: run
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ((docker-hub-username))/concourse-tutorial-hello-world
          run:
            path: /kaniko/executor
            args:
            - builds
            - submit
            - --tag=eu.gcr.io/sre-tooling/test-gradle
          params:
            NAME: ((docker-hub-username))



platform: linux

image_resource:
  type: docker-image
  source:
    repository: eu.gcr.io/sre-tooling/gcloud-build-test
    username: _json_key
    password: ((gcloud-service-account-key-file))

inputs:
  - name: source-code
  - name: xite-sdk
  - name: kubedir

run:
  path: sh
  args:
  - -exc
  - |
    ./xite-sdk/apply-k8s-service.sh

params:
  GCLOUD_SERVICE_ACCOUNT_KEY_FILE: ((gcloud-service-account-key-file))
  DEBUG_DEPLOYMENT_SCRIPT: false
